#!/bin/sh
# Reinitialize pinpoint routing when tun1 comes up (after sing-box start/restart)
# Install to: /etc/hotplug.d/net/99-pinpoint

case "$ACTION" in
    add)
        if [ "$INTERFACE" = "tun1" ] || [ "$DEVICE" = "tun1" ]; then
            logger -t pinpoint "tun1 interface added, initializing routing..."
            sleep 1
            /opt/pinpoint/scripts/pinpoint-init.sh start
        fi
        ;;
esac
